title: Mon Portfolio - Lùca ONALI
email: your-email@example.com
description: Ceci est mon site personnel construit grâce à Jekyll
author: Lùca Onali
github_username:  luca-onali

theme: minima
plugins:
  - jekyll-feed


